#!/usr/bin/env zsh

if [[ $# -eq 0 ]]; then
	exit 1
fi

. /usr/lib/steamos-extension-performance-tuning.zsh

systune /sys/block/$1 \
	queue/add_random 0 \
	queue/io_poll_delay 0 \
	queue/iostats 0 \
	queue/max_sectors_kb 2048 \
	queue/nomerges 1 \
	queue/nr_requests 1024 \
	queue/read_ahead_kb 2048 \
	queue/rq_affinity 2 \
	queue/throttle_sample_time 8
