#!/usr/bin/env zsh

. /usr/lib/steamos-extension-performance-tuning.zsh

# Enable discard on swap devices.
< /proc/swaps while read -r device devtype devsize devuse devprio; do
	if grep -q swapfile <<< $device && [[ $devtype == file ]]; then
		swapoff $device && swapon --discard -p $devprio $device
	fi
done

# baloo is KDE's file indexer. It can be a performance hog sometimes.
for unit in \
	gssuserproxy.socket \
	kde-baloo.service \
	ssh-agent.service
do
	systemctl disable --global $unit
done

# obex is bluetooth file transfer.
for unit in \
	drkonqi-coredump-cleanup.timer \
	obex.service \
	systemd-tmpfiles-clean.timer
do
	systemctl enable --global $unit
done

# Extraneous system services.
for unit in \
	gpu-trace.service \
	steamos-log-submitter.service
do
	systemctl disable --now $unit
done

# Enable multi-gen LRU
systune /sys/kernel/mm/lru_gen \
	enabled 7 \
	min_ttl_ms 0

# Raise file limits. This should occur early enough in the boot to apply
# to everything. We dont bother enforcing persistence here as the extension
# can just reinstall the file on next boot after an update.
upsert /etc/security/limits.d/00-steamos-extension-performance-tuning.conf << EOF
* hard memlock 2147484
* soft memlock 2147484
EOF

# Disable kernel samepage mapping, it kills idle efficiency.
systune /sys/kernel/mm/ksm \
	run 0

# Configure kernel hugepage parameters.
# Disable the defragger to reduce background operations.
systune /sys/kernel/mm/transparent_hugepage \
	enabled always \
	defrag madvise \
	shmem_enabled advise \
	khugepaged/defrag 0

# Turn on transparent hugepages for shared menory.
mount -o remount,huge=advise /tmp
mount -o remount,huge=advise /dev/shm

# Enable TEO cpuidle governor.
systune /sys/devices/system/cpu/cpuidle \
	current_governor teo

sysctl -p- > /dev/null << EOF
# Disable memory compaction to reduce background activity.
vm.compaction_proactiveness=0

# Disable core dumps.
kernel.core_pattern=|/bin/false
kernel.core_pipe_limit=0

# Disable kernwl tracing.
kernel.ftrace_enabled=0

# Disable dnotify, everything uses inotify anyways.
fs.dir-notify-enable=0

# Disable kexec, SteamOS doesn't use it.
kernel.kexec_load_disabled=1
kernel.kexec_load_limit_panic=0
kernel.kexec_load_limit_reboot=0

# Disables the hung task scanner to reduce background activity
kernel.hung_task_timeout_secs=0
kernel.hung_task_check_interval_secs=5

# Enable BPF
kernel.unprivileged_bpf_disabled=0

# Rate limit.peeformance monitoring.
kernel.perf_cpu_time_max_percent=3

# Effectively disable the kernel logger.
kernel.printk=0 0 0 0
kernel.printk_ratelimit_burst=5
kernel.printk_devkmsg=off
debug.exception-trace=0

# Minimize page lock unfairness without disabling it.
vm.page_lock_unfairness=1

# Enable task auto-grouping; this should make latency of tooling like the
# UI overlay better under high load games.
kernel.sched_autogroup_enabled=0

# Double the CFS transfer timeslice to reduce transfer overhead.
kernel.sched_cfs_bandwidth_slice_us=10000

# Parent-runs-first is more cache-friendly, but the child process is usually
# the hotter code.
# https://yarchive.net/comp/linux/child-runs-first.html
kernel.sched_child_runs_first=1

# Disable the energy aware scheduler, the steam deck is heterogeneous.
# See: https://docs.kernel.org/scheduler/sched-energy.html
#   ! EAS does not support platforms with symmetric CPU topologies !
kernel.sched_energy_aware=1

# Set minimal round-robin timeslice. Less efficient, more responsive.
kernel.sched_rr_timeslice_ms=1

# See: https://docs.kernel.org/6.7/scheduler/sched-util-clamp.html
#
# On the other hand, a busy task for instance that requires to run at maximum 
# performance point will suffer a delay of ~200ms (PELT HALFIFE = 32ms) for the
# scheduler to realize that. This is known to affect workloads like gaming on 
# mobile devices where frames will drop due to slow response time to select the
# higher frequency required for the tasks to finish their work in time. Setting
# UCLAMP_MIN=1024 will ensure such tasks will always see the highest performance 
# level when they start running.
kernel.sched_util_clamp_min=1024
kernel.sched_util_clamp_min_rt_default=1024

# Disable task delay accounting to reduce overhead.
kernel.task_delayacct=0

# Enable timer migration to non-idle cores to minimize wakeups.
kernel.timer_migration=1

# Generic network tuning.
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_keepalive_intvl=20
net.ipv4.tcp_keepalive_probes=6
net.ipv4.tcp_keepalive_time=180
net.unix.max_dgram_qlen=8192

# Reserve 3% of system memory.
vm.admin_reserve_kbytes=$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') * 3 / 100 ))

# VM tweaking
vm.dirty_background_ratio=16
vm.dirty_expire_centisecs=12000
vm.dirty_ratio=24
vm.dirty_writeback_centisecs=6000
vm.swappiness=200
vm.vfs_cache_pressure=200
vm.hugetlb_optimize_vmemmap=1

# Recommended value is 1 per 128kB of system RAM.
vm.max_map_count=$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 128 ))

# Recommended is 6% of system memory.
vm.min_free_kbytes=$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') * 6 / 100 ))

# Instruct the OOM killer to immediately kill the task that failed allocation.
# Should make OOM conditions more responsive.
vm.oom_kill_allocating_task=1

# Disable page-clustering on swap since we use zRAM.
vm.page-cluster=0

# Watermark for swap is 33% of RAM. Very aggressive since we have zRAM swap.
vm.watermark_scale_factor=333
vm.watermark_boost_factor=0

# Generic filesystem-related tweaks.
fs.aio-max-nr=131072
fs.epoll.max_user_watches=524288
fs.inotify.max_queued_events=32768
fs.inotify.max_user_watches=1048576
fs.pipe-max-size=2097152

EOF

# Kernel parameter tweaks.
#
# Deliberately not adapted for HoloISO - something in here is causing reboots
# to fail. disable-mitigations works, however.
# FIXME: Add HoloISO support.
if [[ -e /boot/efi/EFI/steamos/grub.cfg ]]; then
	for setting in \
		amd_pstate=active \
		amdgpu.cwsr_enable=0 \
		amdgpu.mes=1 \
		amdgpu.moverate=128 \
		amdgpu.umsch_mm=1 \
		amdgpu.uni_mes=1 \
		drm_kms_helper.poll=0 \
		gbpages \
		mem_encrypt=off \
		nmi_watchdog=0 \
		nohz_full \
		nowatchdog \
		nvme.max_host_mem_size_mb=3072 \
		nvme.sgl_threshold=2097153 \
		nvme.use_cmb_sqes=1 \
		nvme.use_threaded_interrupts=1 \
		nvme_core.admin_timeout=900 \
		nvme_core.io_timeout=4294967295 \
		nvme_core.shutdown_timeout=60 \
		scsi_mod.scan=async \
		transparent_hugepage=always \
		usbhid.jspoll=1 \
		virtio_blk.num_request_queues=8 \
		virtio_blk.poll_queues=16 \
		virtio_blk.queue_depth=2048
	do
		if grep -q $setting /boot/efi/EFI/steamos/grub.cfg; then
			continue
		fi

		sed -i -E 's@^(\s*)steamenv_boot(.*)$@\1steamenv_boot\2 '$setting'@g' /boot/efi/EFI/steamos/grub.cfg
		touch /tmp/.kernel-cmdline-modified
	done
fi

# Optimize system for power consumption.
powertop --auto-tune > /dev/null 2>&1

# Set sefault device schedulers.
# Anything set incorrectly here will be corrected by the block device handlers.
for block in $(ls /sys/block); do
	if ! [[ -f /sys/block/$block/queue/scheduler ]]; then
		continue
	fi

	if \
		[[ -f /sys/block/$1/queue/rotational ]] && \
		[[ 1 -eq $(cat /sys/block/$1/queue/rotational) ]]
	then
		scheduler=bfq
	elif \
		[[ -f /sys/block/$1/removable ]] && \
		[[ 1 -eq $(cat /sys/block/$1/removable) ]]
	then
		scheduler=mq-deadline
	else
		scheduler=kyber
	fi

	upsert /sys/block/$block/queue/scheduler <<< $scheduler
done

# PCI tweaks.
setpci -v -s '*:*' latency_timer=20
setpci -v -s '0:0' latency_timer=0
setpci -v -d "*:*:04xx" latency_timer=80

# Disable atime on any boot-mounted filesystems.
mount \
| grep -E '^/dev/nvme' \
| awk '{print $3}' \
| xargs -rn1 -P$(nproc --all) mount -o remount,noatime

# Perform block device specific optimizations.
# Run in parallel to charging/discharging optimizations.
update-devices zram mmcblk > /dev/null 2>&1 &

# Apply power-state specific optimizations.
if on_ac; then
	/usr/sbin/steamos-extension-performance-tuning-udev-charging > /dev/null 2>&1
else
	/usr/sbin/steamos-extension-performance-tuning-udev-discharging > /dev/null 2>&1 
fi

wait
exit 0
