#!/usr/bin/env zsh

if [[ -f /tmp/.kernel-cmdline-readonly-disabled ]]; then
	rm -f /tmp/.kernel-cmdline-readonly-disabled
	steamos-readonly enable
fi

if [[ -f /tmp/.kernel-cmdline-modified ]]; then
	rm -rf /tmp/.kernel-cmdline-modified
	reboot
fi
