#!/usr/bin/env zsh
set -e

grep -oE '/dev/zram[0-9]+' /proc/swaps | while read -r swap; do
	swapoff $swap
done

if mount | grep -q /home/deck/.zram/ram/mountpoint; then
	mount | grep -E 'on '/home/deck'/[.]zram/ram/mountpoint/[^ ]+ type btrfs' | awk '{print $3}' | while read -r mountpoint; do
		umount -l $mountpoint
		find $mountpoint -mindepth 1 -delete
	done
	mount | grep -E '^zram-overlay' | awk '{print $3}' | grep -vE '^'/home/deck'/[.]zram/ram/mountpoint$' | while read -r mountpoint; do
		umount -l $mountpoint
	done

	mkdir -p /home/deck/.zram/buffer
	rsync -ra --delete --delete-before /home/deck/.zram/ram/mountpoint/ /home/deck/.zram/buffer/
	umount -l /home/deck/.zram/ram/mountpoint
	rm -rf /home/deck/.zram/ram/{mountpoint,changing}
	rsync -ra --delete --delete-before /home/deck/.zram/buffer/ /home/deck/.zram/ram/current/
fi

if mount | grep -q /home/deck/.zram/ram; then
	umount -l /home/deck/.zram/ram
	chown deck:deck -R /home/deck/.zram
fi

sync

if lsmod | grep -q zram; then
	rmmod zram || true
fi

if mount | grep -q '/var/tmp on /var/tmp type tmpfs'; then
	umount -l /var/tmp
fi
