#!/usr/bin/env zsh

if [[ $# -eq 0 ]]; then
	exit 1
fi

. /usr/lib/steamos-extension-performance-tuning.zsh

if \
	[[ -f /sys/block/$1/removable ]] && \
	[[ 1 -eq $(cat /sys/block/$1/removable) ]]
then
	systune /sys/block/$1 \
		queue/scheduler mq-deadline \
else
	systune /sys/block/$1 \
		queue/scheduler kyber \
		queue/iosched/read_lat_nsec 1111333 \
		queue/iosched/write_lat_nsec 3311111
fi

systune /sys/block/$1 \
	device/ncq_prio_enable 1 \
	device/queue_ramp_up_period 1111 \
	queue/add_random 0 \
	queue/io_poll 1 \
	queue/io_poll_delay 0 \
	queue/iostats 0 \
	queue/max_sectors_kb 2048 \
	queue/nr_requests 64 \
	queue/read_ahead_kb 2048 \
	queue/throttle_sample_time 11 \
	queue/wbt_lat_usec 33111
