# Only persist files required by the extension loader itself
# The loader will re-enable systemd-sysext on boot which handles other extensions
/etc/atomic-update.conf.d/steamos-extension-loader.conf
/etc/systemd/system/steamos-extension-loader.service
/etc/systemd/system/sysinit.target.wants/steamos-extension-loader.service
/etc/systemd/system/multi-user.target.wants/steamos-extension-loader-installer.service
/etc/systemd/system/timers.target.wants/steamos-extension-loader-system-cleaner.timer
/etc/steamos-extension-loader
#decky plugin loader
/etc/systemd/system/plugin_loader.service
